version: '3.3'
services:
  nginx:
    restart: always
    image: aweaver/defectdojo-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    environment:
     - DH_SIZE=512
    volumes:
      - django-DefectDojo:/django-DefectDojo
      - nginxdata:/etc/nginx/external/
    depends_on:
      - dojo
    links:
      - dojo
  dojo:
    restart: always
    build: .
    ports:
      - "8000:8000"
    volumes:
      - django-DefectDojo:/opt/django-DefectDojo
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=dojo
      - MYSQL_USER=dojo
      - MYSQL_PASSWORD=test123123sdasdasd221ds

      - DOJO_ADMIN_USER=admin
      - DOJO_ADMIN_NAME=Admin-User
      - DOJO_ADMIN_EMAIL=admin@dojo.local
      - DOJO_ADMIN_PASSWORD=asdijoiwjoi2joeijrASDs21
  mysql:
    restart: always
    image: mysql:5.7
    ports:
      - "3306"
    environment:
      - DOJO_MYSQL_HOST=mysql
      - DOJO_MYSQL_PORT=3306
      - MYSQL_DATABASE=dojo
      - MYSQL_USER=dojo
      - MYSQL_PASSWORD=test123123sdasdasd221ds
      - MYSQL_ROOT_PASSWORD=test123123sdasdasd221dsasdasd2dasd
      - max_allowed_packet=16M
    volumes:
      - mysqldata:/var/lib/mysqldata/data/
volumes:
  mysqldata: {}
  django-DefectDojo: {}
  nginxdata: {}
